name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
  
    runs-on: ${{ matrix.os }}

    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Zip Setup
      if: ${{ matrix.os == 'lwindows-latest' }}
      uses: vimtor/action-zip@v1.1
      with:
        files: build/NexgenReduxSetup.exe
        dest:  build/NexgenReduxSetup-PC.zip
        recursive: false

    - name: Create draft Release
      if: ${{ matrix.os == 'lwindows-latest' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        draft: true
        files: 'build/NexgenReduxSetup-PC.zip'

      



        
        

