name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:

  BUILD_TYPE: Release

jobs:
  
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Install Packages for Mac
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: ConorMacBride/install-package@v1
      with:
        brew-cask: packages
        
    - name: Install Zip for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: montudor/action-zip@v1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Zip Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: vimtor/action-zip@v1.1
      with:
        files: build/NexgenReduxSetup.exe
        dest:  build/NexgenRedux-PC.zip
        recursive: false
        
    - name: Zip Mac
      if: ${{ matrix.os == 'macos-latest' }}
      uses: vimtor/action-zip@v1.1
      with:
        files: build/NexgenRedux.pkg
        dest:  build/NexgenRedux-Mac.zip
        recursive: false

    - name: Create draft Release Windows
      if: ${{ matrix.os == 'macos-latest' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        draft: true
        files: 'build/NexgenRedux-PC.zip'
        
    - name: Create draft Release Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        draft: true
        files: 'build/NexgenRedux-Linux.zip'
        
    - name: Create draft Release Mac
      if: ${{ matrix.os == 'macos-latest' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        draft: true
        files: 'build/NexgenRedux-Mac.zip'
